spring:
  application:
    name: bankcards

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
        batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false

  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration-minutes: 60

  crypto:
    pan:
      key-base64: ${CRYPTO_KEY_BASE64}

server:
  port: ${APP_PORT:8080}
