CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$ BEGIN
    CREATE TYPE users_status AS ENUM ('user', 'admin');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL ,
    email TEXT NOT NULL UNIQUE ,
    user_status users_status NOT NULL DEFAULT 'user',
    password_hash TEXT NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    is_active BOOLEAN DEFAULT TRUE
);

CREATE INDEX users_email_idx ON users(email);
CREATE INDEX users_is_active_idx ON users(is_active);
CREATE INDEX users_user_status_idx ON users(user_status);
--Admin123! - password
INSERT INTO users (name, email, user_status, password_hash)
VALUES ('artem', 'artyom@mail.ru', 'admin', '$2a$10$5.t71MFiwS0UQwIzWkNAIOktkH2nYowcb.xOhxW4xksqtSR/nyzFu');