CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$ BEGIN
    CREATE TYPE cards_status AS ENUM ('active', 'blocked', 'deadline');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS cards(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    pan_enc bytea NOT NULL,
    last4 char(4) NOT NULL,

    card_owner BIGINT REFERENCES users(id) NOT NULL,
    expiry_date date NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    card_status cards_status DEFAULT 'active',
    balance NUMERIC(15, 2) NOT NULL DEFAULT 0.00,

    CONSTRAINT last4_digits CHECK (last4 ~ '^[0-9]{4}$'),

    CONSTRAINT expiry_date_end_of_month CHECK (
    expiry_date = (date_trunc('month', expiry_date::timestamp)
    + interval '1 month' - interval '1 day')::date)
);

CREATE INDEX cards_card_owner_idx ON cards (card_owner);
CREATE INDEX cards_card_status_idx ON cards (card_status);
CREATE INDEX cards_expiry_date_idx ON cards (expiry_date);