DO $$ BEGIN
    CREATE TYPE transactions_status AS ENUM ('delivered', 'expectation', 'rejection');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS transactions(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_card_id BIGINT REFERENCES cards(id) NOT NULL,
    to_card_id BIGINT REFERENCES cards(id) NOT NULL,
    amount NUMERIC(15, 2) NOT NULL CHECK (amount > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    transaction_status transactions_status NOT NULL DEFAULT 'expectation',
    comment VARCHAR(200)
);

CREATE INDEX transactions_transaction_status_idx ON transactions (transaction_status);
CREATE INDEX transactions_from_card_id_idx ON transactions (from_card_id);
CREATE INDEX transactions_to_card_id_idx   ON transactions (to_card_id);
