CREATE TYPE block_request_status AS ENUM ('pending', 'approved', 'rejected', 'canceled');

CREATE TABLE IF NOT EXISTS card_block_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    card_id BIGINT NOT NULL REFERENCES cards(id),
    user_id BIGINT NOT NULL REFERENCES users(id),

    reason TEXT NOT NULL,
    status block_request_status NOT NULL DEFAULT 'pending',

    created_at timestamptz NOT NULL DEFAULT now(),
    processed_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_block_request_one_pending_per_card
    ON card_block_requests(card_id)
    WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_cards_owner
    ON cards(card_owner);
CREATE INDEX IF NOT EXISTS idx_cards_owner_status
    ON cards(card_owner, card_status);
CREATE INDEX IF NOT EXISTS idx_cards_owner_last4
    ON cards(card_owner, last4);
CREATE INDEX IF NOT EXISTS idx_cards_owner_created_at
    ON cards(card_owner, created_at DESC);